export const CHANGE_FOCUS = 'CHANGE_FOCUS';
export const CHANGE_CURRENCY_VALUE = 'CHANGE_CURRENCY_VALUE';
export const CHANGE_CURRENCY_CODE = 'CHANGE_CURRENCY_CODE';
export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const EXCHANGE_AMOUNT = 'EXCHANGE_AMOUNT';
export const FETCH_CURRENCY_RATES = 'FETCH_CURRENCY_RATES';
export const FETCH_CURRENCY_RATES_SUCCESS = 'FETCH_CURRENCY_RATES_SUCCESS';
export const FETCH_CURRENCY_RATES_ERROR = 'FETCH_CURRENCY_RATES_ERROR';
